from django.utils import timezone
from django.db import models

class Tournament(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=40, default='')
    email = models.CharField(max_length=40, default='')
    when = models.CharField(max_length=40, default=timezone.now())
    tournament_name = models.CharField(max_length=40, default='')
    tournament_game = models.CharField(max_length=20, default='')
    tournament_url = models.CharField(max_length=20, default='')
    streaming_url = models.CharField(max_length=20, default='')
    streaming_url_spec = models.CharField(max_length=20, default='')
    tournament_type = models.CharField(max_length=20, default='')
    tournament_format = models.CharField(max_length=20, default='')
    tournament_spec = models.CharField(max_length=200, default='')
    registration = models.CharField(max_length=20, default='')
    registration_team = models.CharField(max_length=20, default='')
    participant = models.CharField(max_length=20, default='')
    starttime = models.CharField(max_length=20, default='')
    checkin = models.CharField(max_length=20, default='')
    checkin_time = models.CharField(max_length=20, default='')
    description = models.TextField(max_length=2000, default='')
    funding = models.CharField(max_length=20, default='')
    promise = models.CharField(max_length=400, default='')
    reward = models.CharField(max_length=400, default='')
    template = models.CharField(max_length=40, default='')
    phone = models.CharField(max_length=20, default='')
    letsmake = models.CharField(max_length=20, default='not_yet')