from django.db import models

class Making(models.Model):
    username = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    tournament_name = models.CharField(max_length=30)
    tournament_game = models.CharField(max_length=30)
    tournament_url = models.CharField(max_length=30)
    streaming_url = models.CharField(max_length=30)
    streaming_url_spec = models.CharField(max_length=30)
    tournament_type = models.CharField(max_length=200)
    registration = models.CharField(max_length=30)
    registration_team = models.CharField(max_length=30)
    participant = models.CharField(max_length=30)
    starttime = models.CharField(max_length=30)
    checkin = models.CharField(max_length=30)
    checkin_time = models.CharField(max_length=30)
    description = models.TextField(max_length=2000)
    funding = models.CharField(max_length=30)
    promise = models.CharField(max_length=200)
    promise_spec = models.CharField(max_length=200)
    reward = models.CharField(max_length=200)
    reward_spec = models.CharField(max_length=200)
    template = models.CharField(max_length=30)
    phone = models.CharField(max_length=30)