# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 28, 8, 0, 24, 949069)),
        ),
    ]
