# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 23:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_signup_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 27, 23, 17, 52, 48112, tzinfo=utc)),
        ),
    ]
