# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160728_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 28, 17, 32, 53, 764379, tzinfo=utc)),
        ),
    ]
