# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160729_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
