# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160729_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
