# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 00:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160802_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 2, 9, 48, 52, 610630)),
        ),
    ]
