# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160810_0711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
