# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0011_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Making',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
    ]
