# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_making'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('tournament_name', models.CharField(max_length=30)),
                ('tournament_game', models.CharField(max_length=30)),
                ('tournament_url', models.CharField(max_length=30)),
                ('streaming_url', models.CharField(max_length=30)),
                ('streaming_url_spec', models.CharField(max_length=30)),
                ('tournament_type', models.CharField(max_length=200)),
                ('registration', models.CharField(max_length=30)),
                ('registration_team', models.CharField(max_length=30)),
                ('participant', models.CharField(max_length=30)),
                ('starttime', models.CharField(max_length=30)),
                ('checkin', models.CharField(max_length=30)),
                ('checkin_time', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=2000)),
                ('funding', models.CharField(max_length=30)),
                ('promise', models.CharField(max_length=200)),
                ('promise_spec', models.CharField(max_length=200)),
                ('reward', models.CharField(max_length=200)),
                ('reward_spec', models.CharField(max_length=200)),
                ('template', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Making',
        ),
    ]
