# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160826_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='promise_spec',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='reward_spec',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='promise',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reward',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 8, 29, 8, 49, 46, 286122, tzinfo=utc), max_length=40),
        ),
    ]
