# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160829_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 8, 29, 8, 51, 16, 265639, tzinfo=utc), max_length=40),
        ),
    ]
