# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20160829_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=40)),
                ('orderno', models.CharField(default='', max_length=40)),
                ('amount', models.CharField(default='', max_length=40)),
                ('paytoken', models.CharField(default=datetime.datetime(2016, 9, 14, 0, 45, 13, 584313, tzinfo=utc), max_length=40)),
                ('when', models.CharField(default=datetime.datetime(2016, 9, 14, 0, 45, 13, 584571, tzinfo=utc), max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 9, 14, 0, 45, 13, 585249, tzinfo=utc), max_length=40),
        ),
    ]
