# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20160914_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='paytoken',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 9, 14, 0, 46, 40, 282531, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 9, 14, 0, 46, 40, 283408, tzinfo=utc), max_length=40),
        ),
    ]
