# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20160914_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_format',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_spec',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_type',
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 17, 9, 34, 36, 413573, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='letsmake',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 17, 9, 34, 36, 414404, tzinfo=utc), max_length=40),
        ),
    ]
