# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20161025_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Making',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=40)),
                ('when', models.CharField(default=datetime.datetime(2016, 10, 25, 2, 51, 55, 573680, tzinfo=utc), max_length=40)),
                ('tournament_name', models.CharField(default='', max_length=40)),
                ('tournament_game', models.CharField(default='', max_length=20)),
                ('tournament_url', models.CharField(default='', max_length=20)),
                ('streaming_url', models.CharField(default='', max_length=20)),
                ('streaming_url_spec', models.CharField(default='', max_length=20)),
                ('registration', models.CharField(default='', max_length=20)),
                ('registration_team', models.CharField(default='', max_length=20)),
                ('participant', models.CharField(default='', max_length=20)),
                ('starttime', models.CharField(default='', max_length=20)),
                ('checkin', models.CharField(default='', max_length=20)),
                ('checkin_time', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='', max_length=2000)),
                ('funding', models.CharField(default='', max_length=20)),
                ('promise', models.CharField(default='', max_length=200)),
                ('promise_spec', models.CharField(default='', max_length=200)),
                ('reward', models.CharField(default='', max_length=200)),
                ('reward_spec', models.CharField(default='', max_length=200)),
                ('template', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=20)),
                ('letsmake', models.CharField(default='no', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 25, 2, 51, 55, 572864, tzinfo=utc), max_length=40),
        ),
    ]
