# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20161025_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='making',
            old_name='letsmake',
            new_name='confirm',
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 25, 4, 31, 46, 392350, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 25, 4, 31, 46, 393158, tzinfo=utc), max_length=40),
        ),
    ]
