# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20161025_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='making',
            old_name='funding',
            new_name='endtime',
        ),
        migrations.AddField(
            model_name='making',
            name='cover_image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='making',
            name='funder',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='making',
            name='funding_goal',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='making',
            name='funding_now',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='making',
            name='main_image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='making',
            name='match_image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='making',
            name='poster_image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='making',
            name='summary',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 25, 5, 15, 42, 528154, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 25, 5, 15, 42, 528909, tzinfo=utc), max_length=40),
        ),
    ]
