# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20161025_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 26, 6, 27, 23, 29115, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 26, 6, 27, 23, 29883, tzinfo=utc), max_length=40),
        ),
    ]
