# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20161026_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 26, 6, 43, 48, 280376, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 26, 6, 43, 48, 281222, tzinfo=utc), max_length=40),
        ),
    ]
