# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20161028_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='tournament_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funding',
            name='tournament_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 31, 5, 9, 26, 742485, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 31, 5, 9, 26, 743340, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 31, 5, 9, 26, 744657, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 10, 31, 5, 9, 26, 745169, tzinfo=utc), max_length=40),
        ),
    ]
