# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 04:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20161031_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.CharField(default='', max_length=20)),
                ('tournament_name', models.CharField(default='', max_length=40)),
                ('username', models.CharField(default='', max_length=40)),
                ('teamname', models.CharField(default='', max_length=40)),
                ('teammember', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=20)),
                ('etc1', models.CharField(default='', max_length=40)),
                ('etc2', models.CharField(default='', max_length=40)),
                ('etc3', models.CharField(default='', max_length=40)),
                ('when', models.CharField(default=datetime.datetime(2016, 11, 1, 4, 57, 55, 409822, tzinfo=utc), max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='amount',
            new_name='tournament_name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='amount',
            new_name='tournament_name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='email',
            new_name='video_name',
        ),
        migrations.RemoveField(
            model_name='making',
            name='funder',
        ),
        migrations.RemoveField(
            model_name='making',
            name='funding_now',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='orderno',
        ),
        migrations.RemoveField(
            model_name='video',
            name='orderno',
        ),
        migrations.RemoveField(
            model_name='video',
            name='username',
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reply',
            name='tournament_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='tournament_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 4, 57, 55, 406502, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 4, 57, 55, 407325, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 4, 57, 55, 408598, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 4, 57, 55, 409107, tzinfo=utc), max_length=40),
        ),
    ]
