# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20161101_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 6, 3, 40, 976263, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='summary',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 6, 3, 40, 977141, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participant',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 6, 3, 40, 979723, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 6, 3, 40, 978467, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 6, 3, 40, 979001, tzinfo=utc), max_length=40),
        ),
    ]
