# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 06:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20161101_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 6, 14, 36, 804587, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='description',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 6, 14, 36, 805561, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participant',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 6, 14, 36, 808320, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 6, 14, 36, 806955, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 6, 14, 36, 807535, tzinfo=utc), max_length=40),
        ),
    ]
