# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20161101_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='amount',
            field=models.IntegerField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 7, 6, 10, 38768, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='description',
            field=models.TextField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 7, 6, 10, 39608, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participant',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 7, 6, 10, 42077, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 7, 6, 10, 40858, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 1, 7, 6, 10, 41373, tzinfo=utc), max_length=40),
        ),
    ]
