# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20161102_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.CharField(default='', max_length=20)),
                ('tournament_name', models.CharField(default='', max_length=40)),
                ('username', models.CharField(default='', max_length=40)),
                ('teamname', models.CharField(default='', max_length=40)),
                ('teammember', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=20)),
                ('etc1', models.CharField(default='', max_length=40)),
                ('etc2', models.CharField(default='', max_length=40)),
                ('etc3', models.CharField(default='', max_length=40)),
                ('when', models.CharField(default=datetime.datetime(2016, 11, 3, 3, 33, 7, 499309, tzinfo=utc), max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.AlterField(
            model_name='funding',
            name='amount',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 3, 33, 7, 495933, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 3, 33, 7, 496817, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 3, 33, 7, 498070, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 3, 33, 7, 498577, tzinfo=utc), max_length=40),
        ),
    ]
