# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20161108_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='confirm',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 7, 53, 4, 788173, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 7, 53, 4, 789046, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 7, 53, 4, 791554, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 7, 53, 4, 790296, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 7, 53, 4, 790815, tzinfo=utc), max_length=40),
        ),
    ]
