# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20161111_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundingdummy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.CharField(default='', max_length=20)),
                ('tournament_name', models.CharField(default='', max_length=40)),
                ('username', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=40)),
                ('orderno', models.CharField(default='', max_length=40)),
                ('amount', models.IntegerField(default='')),
                ('when', models.CharField(default=datetime.datetime(2016, 11, 11, 7, 59, 51, 242405, tzinfo=utc), max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='reply',
            name='confirm',
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 7, 59, 51, 241395, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 7, 59, 51, 242958, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 7, 59, 51, 245586, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 7, 59, 51, 244282, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 7, 59, 51, 244929, tzinfo=utc), max_length=40),
        ),
    ]
