# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 05:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20161121_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='thankyou',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 24, 16, 56347, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='thankyou',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 24, 16, 54740, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='confirm',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 24, 16, 57739, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 24, 16, 60991, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 24, 16, 59769, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 24, 16, 60338, tzinfo=utc), max_length=40),
        ),
    ]
