# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 05:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20161121_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='thankyou',
        ),
        migrations.RemoveField(
            model_name='fundingdummy',
            name='thankyou',
        ),
        migrations.AlterField(
            model_name='funding',
            name='amount',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 27, 54, 196542, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='amount',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 27, 54, 197467, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 27, 54, 197979, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 27, 54, 200514, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 27, 54, 199257, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 5, 27, 54, 199858, tzinfo=utc), max_length=40),
        ),
    ]
