# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 07:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_auto_20161121_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='result',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participation',
            name='score',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 7, 43, 2, 650152, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 7, 43, 2, 649059, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 7, 43, 2, 650860, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 7, 43, 2, 653926, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 7, 43, 2, 652563, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 7, 43, 2, 653194, tzinfo=utc), max_length=40),
        ),
    ]
