# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-26 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20161121_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='making',
            old_name='endtime',
            new_name='funding_endtime',
        ),
        migrations.RenameField(
            model_name='making',
            old_name='starttime',
            new_name='funding_starttime',
        ),
        migrations.AddField(
            model_name='funding',
            name='comment',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fundingdummy',
            name='comment',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='making',
            name='participation_endtime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='making',
            name='participation_starttime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 0, 36, 620384, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 0, 36, 618769, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 0, 36, 620959, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 0, 36, 623596, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 0, 36, 622375, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 0, 36, 622938, tzinfo=utc), max_length=40),
        ),
    ]
