# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-26 09:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_auto_20161126_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='making',
            old_name='funding_starttime',
            new_name='starttime',
        ),
        migrations.RemoveField(
            model_name='making',
            name='participation_starttime',
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 20, 35, 965810, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 20, 35, 964816, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 20, 35, 966358, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 20, 35, 968922, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 20, 35, 967748, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 9, 20, 35, 968264, tzinfo=utc), max_length=40),
        ),
    ]
