# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 04:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20161126_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='checkin',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='participation',
            name='confirm',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='funding',
            name='reward',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 28, 4, 11, 31, 709427, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 28, 4, 11, 31, 707864, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 28, 4, 11, 31, 709988, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='result',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='score',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 28, 4, 11, 31, 712529, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 28, 4, 11, 31, 711366, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 11, 28, 4, 11, 31, 711878, tzinfo=utc), max_length=40),
        ),
    ]
