# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 12:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_auto_20161230_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 12, 30, 12, 58, 39, 117450, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 12, 30, 12, 58, 39, 115928, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='description',
            field=models.TextField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 12, 30, 12, 58, 39, 118168, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 12, 30, 12, 58, 39, 120998, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2016, 12, 30, 12, 58, 39, 119669, tzinfo=utc), max_length=40),
        ),
    ]
