# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_auto_20170109_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
