# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_auto_20170109_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='making',
            name='notice',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 9, 6, 29, 38, 473852, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 9, 6, 29, 38, 472882, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='description',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 9, 6, 29, 38, 474444, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 9, 6, 29, 38, 476767, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 9, 6, 29, 38, 476072, tzinfo=utc), max_length=40),
        ),
    ]
