# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-13 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_auto_20170111_1719'),
    ]

    operations = [
        migrations.RenameModel('making', 'tournament')
    ]
