# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_auto_20170117_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 17, 1, 56, 58, 381090, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 17, 1, 56, 58, 380108, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='help',
            name='answer',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='making',
            name='description',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
        migrations.AlterField(
            model_name='making',
            name='notice',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 17, 1, 56, 58, 381671, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 17, 1, 56, 58, 383822, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 17, 1, 56, 58, 383153, tzinfo=utc), max_length=40),
        ),
    ]
