# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 05:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0128_auto_20170119_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_game', models.CharField(default='', max_length=20)),
                ('tournament_type', models.CharField(default='', max_length=20)),
                ('content', django_summernote.fields.SummernoteTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 19, 5, 47, 29, 523444, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 19, 5, 47, 29, 524374, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 19, 5, 47, 29, 526555, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 19, 5, 47, 29, 525861, tzinfo=utc), max_length=40),
        ),
    ]
