# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-25 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_auto_20170124_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usage', models.CharField(default='', max_length=20)),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tournament_name', models.CharField(default='', max_length=40)),
                ('tournament_image', models.CharField(default='', max_length=200)),
                ('tournament_summary', django_summernote.fields.SummernoteTextField()),
                ('tournament_game', models.CharField(default='', max_length=40)),
                ('tournament_url', models.CharField(default='', max_length=40)),
                ('tournament_rule', django_summernote.fields.SummernoteTextField()),
                ('registration_type', models.CharField(default='', max_length=20)),
                ('participation_form', models.CharField(default='', max_length=200)),
                ('participation_number', models.CharField(default='', max_length=20)),
                ('participation_starttime', models.CharField(default='', max_length=20)),
                ('participation_endtime', models.CharField(default='', max_length=20)),
                ('participation_checkin', models.CharField(default='', max_length=20)),
                ('participation_fee', models.CharField(default='', max_length=20)),
                ('funding', models.CharField(default='', max_length=20)),
                ('reward', models.CharField(default='', max_length=200)),
                ('reward_spec', models.CharField(default='', max_length=200)),
                ('promise', models.CharField(default='', max_length=200)),
                ('promise_spec', models.CharField(default='', max_length=200)),
                ('user_image', models.CharField(default='', max_length=200)),
                ('user_name', models.CharField(default='', max_length=40)),
                ('user_introduction', django_summernote.fields.SummernoteTextField()),
                ('streaming_url', models.CharField(default='', max_length=200)),
                ('user_email', models.CharField(default='', max_length=40)),
                ('user_phone', models.CharField(default='', max_length=20)),
                ('creater_enrollment', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 25, 9, 36, 46, 899198, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 25, 9, 36, 46, 900293, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 25, 9, 36, 46, 905198, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 25, 9, 36, 46, 904235, tzinfo=utc), max_length=40),
        ),
    ]
