# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_auto_20170125_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='cover_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 26, 9, 13, 57, 513506, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 26, 9, 13, 57, 514441, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 26, 9, 13, 57, 517879, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 1, 26, 9, 13, 57, 517212, tzinfo=utc), max_length=40),
        ),
    ]
