# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 07:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_auto_20170216_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='etc5',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='participation',
            name='etc6',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 2, 16, 7, 48, 35, 697007, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 2, 16, 7, 48, 35, 695934, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 2, 16, 7, 48, 35, 697606, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 2, 16, 7, 48, 35, 702561, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 2, 16, 7, 48, 35, 701803, tzinfo=utc), max_length=40),
        ),
    ]
