# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0148_auto_20170227_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chat',
            name='tournament_name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='path',
            field=models.CommaSeparatedIntegerField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tournament_name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='funding',
            name='email',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='funding',
            name='orderno',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='funding',
            name='reward',
            field=models.CharField(default='-', max_length=1000),
        ),
        migrations.AlterField(
            model_name='funding',
            name='thanks',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='funding',
            name='tournament_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='funding',
            name='tournament_name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='funding',
            name='username',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 2, 27, 7, 0, 55, 895069, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='email',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='orderno',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='reward',
            field=models.CharField(default='-', max_length=1000),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='thanks',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='tournament_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='tournament_name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='username',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 2, 27, 7, 0, 55, 893095, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='gamerule',
            name='tournament_game',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamerule',
            name='tournament_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='help',
            name='question',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='help',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='usage',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='checkin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='checkin_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='confirm',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='cover_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='making',
            name='email',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='funding_endtime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='funding_goal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='main_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='making',
            name='match_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='making',
            name='participant',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='participation_endtime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='poster_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='making',
            name='promise',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='making',
            name='promise_spec',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='making',
            name='registration',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='registration_team',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='reward',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='making',
            name='reward_spec',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='making',
            name='starttime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='streaming_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='streaming_url_spec',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='template',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='tournament_game',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='tournament_name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='tournament_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='making',
            name='username',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 2, 27, 7, 0, 55, 896197, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='checkin',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='participation',
            name='confirm',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='participation',
            name='email',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='etc1',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='etc2',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='etc3',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='etc4',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='etc5',
            field=models.CharField(default='-', max_length=2000),
        ),
        migrations.AlterField(
            model_name='participation',
            name='etc6',
            field=models.CharField(default='-', max_length=2000),
        ),
        migrations.AlterField(
            model_name='participation',
            name='name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='participation',
            name='prize',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='result',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='score',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='teammember',
            field=models.CharField(default='-', max_length=2000),
        ),
        migrations.AlterField(
            model_name='participation',
            name='teamname',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='tournament_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='participation',
            name='tournament_name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='username',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 2, 27, 7, 0, 55, 902319, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='account_notice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='confirm',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='cover_image',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='creator_enrollment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='email',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='funding',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='funding_endtime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='funding_goal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='funding_notice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='funding_starttime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='funding_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo_image',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_checkin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_checkin_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_endtime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_fee',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_fee_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_starttime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_template',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='profile_account',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='profile_email',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='profile_email_question',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='profile_image',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='profile_name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='profile_name_question',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='profile_phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='promise',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='promise_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='promise_spec',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reward',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reward_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reward_spec',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='streaming_site',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='streaming_url',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_endtime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_game',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_game_etc',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_image',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_starttime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_url',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='username',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='video',
            name='tournament_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='tournament_name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 2, 27, 7, 0, 55, 901471, tzinfo=utc), max_length=400),
        ),
    ]
