# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-12 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0151_auto_20170308_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='registration',
            new_name='participation',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='registration_type',
            new_name='participation_type',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='streaming_url',
            new_name='streaming',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='funding_time',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='participation_checkin_time',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='participation_fee_number',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='participation_time',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='profile_email_question',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='profile_name_question',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='promise_number',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='promise_spec',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='reward_number',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='reward_spec',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='streaming_site',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_format_spec_detail',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_game_etc',
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 12, 7, 2, 16, 251649, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 12, 7, 2, 16, 250571, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 12, 7, 2, 16, 252396, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 12, 7, 2, 16, 256036, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='promise',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reward',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 12, 7, 2, 16, 255354, tzinfo=utc), max_length=400),
        ),
    ]
