# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 01:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0153_auto_20170312_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='funding_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participation_custom_url',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participation_template_custom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participation_template_format',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participation_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='promise_number',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='tournament',
            name='promise_spec',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='tournament',
            name='reward_number',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='tournament',
            name='reward_spec',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='tournament',
            name='streaming_site',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='tournament',
            name='streaming_url',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 15, 1, 59, 26, 614550, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 15, 1, 59, 26, 613016, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 15, 1, 59, 26, 615303, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 15, 1, 59, 26, 619473, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='promise',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reward',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='streaming',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 15, 1, 59, 26, 618758, tzinfo=utc), max_length=400),
        ),
    ]
