# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 05:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0164_auto_20170321_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='comment2',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='fundingdummy',
            name='comment2',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 21, 5, 56, 0, 17264, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 21, 5, 56, 0, 14792, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 21, 5, 56, 0, 18424, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 21, 5, 56, 0, 23397, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 21, 5, 56, 0, 22581, tzinfo=utc), max_length=400),
        ),
    ]
