# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0166_auto_20170321_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 22, 6, 17, 52, 372277, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 22, 6, 17, 52, 371013, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 22, 6, 17, 52, 372874, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='etc3',
            field=models.CharField(default='-', max_length=2000),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 22, 6, 17, 52, 376861, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 22, 6, 17, 52, 376154, tzinfo=utc), max_length=400),
        ),
    ]
