# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-25 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0168_auto_20170323_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='challonge_url',
            field=models.CharField(default='-', max_length=2000),
        ),
        migrations.AddField(
            model_name='tournament',
            name='notice',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
        migrations.AddField(
            model_name='tournament',
            name='video_url',
            field=models.CharField(default='[]', max_length=4000),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 25, 9, 11, 7, 138230, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 25, 9, 11, 7, 137026, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 25, 9, 11, 7, 138806, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 25, 9, 11, 7, 142766, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_template',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_template_format',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='profile_account',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='profile_phone',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='promise_number',
            field=models.CharField(default='[]', max_length=4000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='promise_spec',
            field=models.CharField(default='[]', max_length=4000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reward_number',
            field=models.CharField(default='[]', max_length=4000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reward_spec',
            field=models.CharField(default='[]', max_length=4000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_format_spec',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 25, 9, 11, 7, 142085, tzinfo=utc), max_length=400),
        ),
    ]
