# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-30 11:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0171_auto_20170329_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='teammember',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='teamname',
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 30, 11, 23, 20, 288345, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 30, 11, 23, 20, 287118, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 30, 11, 23, 20, 289033, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 30, 11, 23, 20, 293292, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 30, 11, 23, 20, 292583, tzinfo=utc), max_length=400),
        ),
    ]
