# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-31 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0176_auto_20170331_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 31, 5, 46, 42, 663296, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 31, 5, 46, 42, 662010, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 31, 5, 46, 42, 663942, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='input',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 31, 5, 46, 42, 668328, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 31, 5, 46, 42, 667573, tzinfo=utc), max_length=400),
        ),
    ]
