# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-31 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0178_auto_20170331_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 31, 10, 43, 59, 499626, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 31, 10, 43, 59, 498130, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 31, 10, 43, 59, 500749, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 31, 10, 43, 59, 506017, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='notice',
            field=django_summernote.fields.SummernoteTextField(default='공지사항 및 변경사항을 입력해주세요.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 3, 31, 10, 43, 59, 504826, tzinfo=utc), max_length=400),
        ),
    ]
