# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-02 12:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0179_auto_20170331_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='dummy_username',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 2, 12, 58, 4, 174787, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 2, 12, 58, 4, 172808, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 2, 12, 58, 4, 175474, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 2, 12, 58, 4, 180011, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 2, 12, 58, 4, 179267, tzinfo=utc), max_length=400),
        ),
    ]
