# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-14 05:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0186_auto_20170414_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='chollonge_start',
            new_name='challonge_start',
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 14, 5, 24, 57, 219310, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 14, 5, 24, 57, 217986, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 14, 5, 24, 57, 219948, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 14, 5, 24, 57, 224298, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created',
            field=models.CharField(default=datetime.datetime(2017, 4, 14, 5, 24, 57, 221268, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 14, 5, 24, 57, 223560, tzinfo=utc), max_length=400),
        ),
    ]
