# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-29 02:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0192_auto_20170422_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 29, 2, 10, 58, 480962, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 29, 2, 10, 58, 479716, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='cover_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='making',
            name='main_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='making',
            name='match_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='making',
            name='poster_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 29, 2, 10, 58, 481571, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 29, 2, 10, 58, 485757, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created',
            field=models.CharField(default=datetime.datetime(2017, 4, 29, 2, 10, 58, 482876, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 4, 29, 2, 10, 58, 485027, tzinfo=utc), max_length=400),
        ),
    ]
