# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0201_auto_20170705_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='donation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='donation_site',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='tournament',
            name='donation_url',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 8, 32, 51, 340220, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 8, 32, 51, 338996, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 8, 32, 51, 340810, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 8, 32, 51, 345092, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 8, 32, 51, 342105, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 8, 32, 51, 344373, tzinfo=utc), max_length=400),
        ),
    ]
