# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 09:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0202_auto_20170708_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 9, 21, 11, 148926, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='fundingdummy',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 9, 21, 11, 147593, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='making',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 9, 21, 11, 149601, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='participation',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 9, 21, 11, 154840, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='account_notice',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 9, 21, 11, 151249, tzinfo=utc), max_length=400),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='funding',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='funding_notice',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participation_fee',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='when',
            field=models.CharField(default=datetime.datetime(2017, 7, 8, 9, 21, 11, 153870, tzinfo=utc), max_length=400),
        ),
    ]
